[package]
name = "csv-validator-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
csv = "1.3.1"
nom = "8.0.0"
bytes = "1.10.1"
pyo3 = { version = "0.24.0", features = ["extension-module", "serde", "indexmap"], optional = true  }

[features]
python = ["pyo3"]